### ISSUE TITLE
Wrong currency symbol in order payment actions

### ISSUE THREAD

**Issue by stefanmf** [ePay/woocommerce#10]
The payment actions widget on orders shows currency symbol different from the currency code of the payment. See attached screenshot — order was placed in Euros (consistent with currency code 978), but window shows DKK.

![screenshot](https://cloud.githubusercontent.com/assets/9478534/12443967/2dc38c20-bf5c-11e5-85af-804efc3e54b2.png)

**Comment by sorenla** [comment]
Hello Stefan

Thank you for reporting this. It has been fixed in the [latest release](https://github.com/ePay/woocommerce/releases/latest).
