### ISSUE TITLE
Warning: preg_replace() [function.preg-replace <http://php.net/manual/en/function.preg-replace>]: The /e modifier is no longer supported, use preg_replace_callback instead

### ISSUE THREAD

**Issue by ghost** [ePay/woocommerce#12]
I am using PHP7, Wordpress 4.4.2 and WooCommerce 2.5.5.
When the payment window is showing, i get the error message:

Warning: preg_replace() [function.preg-replace <http://php.net/manual/en/function.preg-replace>]: The /e modifier is no longer supported, use preg_replace_callback instead

I have changed the following from:
private function jsonRemoveUnicodeSequences($struct)
{
return preg_replace("/\\\\u([a-f0-9]{4})/e", "iconv('UCS-4LE','UTF-8',pack('V', hexdec('U$1')))", json_encode($struct));
}
	
To this:
private function jsonRemoveUnicodeSequences($struct)
{
   return preg_replace_callback(
   "/\\\\u([a-f0-9]{4})/", 
   function($m) { return "iconv('UCS-4LE','UTF-8',pack('V', hexdec('U$m[1]')))"; }, 
   json_encode($struct));
}

The warning no longer shows up, but I am not that good with regular expressions, so can anyone tell me if this is ok?

Jon Kristensen
http://jojoweb.dk

**Comment by robman87** [comment]
There was an error in your code, you almost got it though :)
It's fixed in #18 (b90245c). Waiting for maintainer to approve pull request.

**Comment by AllanWLie** [comment]
Your issue is solved in the latest release
