### ISSUE TITLE
Incompatibility with CloudFlare's Wordpress plugin

### ISSUE THREAD

**Issue by jonasskafte** [ePay/woocommerce#13]
Hi there,

I recently experienced that the ePay module on my site went from working fine to suddenly not working at all. I spent some time trying to work out what the issue was and I had several conversations with the ePay support team as well as with the theme developers of the theme that I'm using. In the end I worked out that it has to do with an incompatibility issue between CloudFlare's Wordpress plug-in, which prevent infinite redirect loops when loading WordPress sites under CloudFlare's Flexible SSL system, and the ePay module.

I don't think I actually need this functionality anyway, and so I've simply deactivated the CloudFlare plugin for now. However, I thought I would still report the problem here, in case it should be of interest to fix it (ideally ePay would work with CloudFlare seamlessly).

Here are a few points that might be relevant:

1) I think – but I'm really not sure! – that perhaps the issue occurred when the CloudFlare plugin was updated to version 1.3.20 (from the changelog: "_• Updated the method to restore visitor IPs,
• Updated the URL rewrite to be compatible with WordPress 4.4_").

2) Here's more about CloudFlare's Flexible SSL system, which might be relevant: https://blog.cloudflare.com/flexible-ssl-wordpress-fixing-mixed-content-errors/

3) A member of the ePay support team also referenced step 6 on this page, suggesting that it has to do with it being impossible to white-list all the IP addresses of the ePay gateway: https://support.cloudflare.com/hc/en-us/articles/201897700-Recommended-First-Steps-for-all-CloudFlare-users

NB. In regards to point 3, I think that sounds likely to be the root of the problem, however, everything works well for me now that I've disabled the Wordpress plugin-in, but I'm still running the site on CloudFlare without white-listing IP addresses, which makes me think that perhaps it has to do with the plug-in and not CloudFlare as such – but then again, I don't know much about the technicalities of the plug-in and CloudFlare and how they work together.

Hope this reporting is helpful to make the ePay module better and stronger.

Thanks,

Jonas

**Comment by sorenla** [comment]
Hello Jonas

Thank you for reporting this. I agree that supporting CloudFlare's Wordpress plugin would be ideal, but unfortunately this is not a priority for our payment plugin right now.
