### ISSUE TITLE
epay not working anymore after updating to Wordpress 4.5

### ISSUE THREAD

**Issue by gorossil** [ePay/woocommerce#14]
Hi ePay,

After updating to Wordpress 4.5 the Epay window is not showing anymore, when i push the pay button, it waits 45 seconds and then the following error occurs : "Beklager, denne ordre er ugyldig, og kan ikke betales for.", "Sorry this order is invalid, and cannot be paid for".

/br
Jan R
<img width="1680" alt="skaermbillede 2016-04-26 kl 11 49 54" src="https://cloud.githubusercontent.com/assets/210633/14814098/0861c056-0ba5-11e6-95a9-0b1eafd1a983.png">

**Comment by ePayRobin** [comment]
Hi Jan

I just testet your checkout on a couple of different browsers. The problem you are experiencing is entirely unrelated to the payment module. I suggest that you try swapping to another theme to see if there are any changes in the result. Perhaps there are compatibility issues between the two. Ultimately the checkout never reaches the page, where the payment software is initiated, which makes it difficult for us to debug.
