### ISSUE TITLE
Brug af forældet class

### ISSUE THREAD

**Issue by martinkolle** [ePay/woocommerce#16]
`Notice: WC_Subscriptions_Order::order_contains_subscription har været forældet siden version 2.0! Brug wcs_order_contains_subscription( $order ) i stedet. in /xxxx/public_html/wp-includes/functions.php on line 3658
`

Det er på linje 236 og 243 i filen woocommerce-gateway-epay-dk.php

**Comment by robman87** [comment]
Fixat i pull request #18 (fd23df7) med fall-back för äldre versioner av WooCommerce Subscriptions.

**Comment by sorenla** [comment]
Hej Martin

Tak for at gøre os opmærksom på dette. Den rettelse @robman87 har foreslået er inkluderet i [seneste release](https://github.com/ePay/woocommerce/releases/latest).
