### ISSUE TITLE
New Order Email

### ISSUE THREAD

**Issue by rjgough** [ePay/woocommerce#17]
Cannot locate the problem however when playing a new order with paypal, the system generates a new order email - however when plaing an order with this plugin, the system doesnt generate any new order emails..

**Comment by ePayRobin** [comment]
Hi Ryan

The most likely reason for this, would be that the callback-requests from our payment server is declined by your webserver. Would you mind creating a ticket by writing our support-email? Please write to support@epay.eu and include your merchant number, then we can help you resolve it.

Kind regards
Robin, ePay Support
