### ISSUE TITLE
Undefined index: enableinvoice

### ISSUE THREAD

**Issue by conveydk** [ePay/woocommerce#19]
After checkout following error is displayed on landing page:

Notice: Undefined index: enableinvoice in wp-content/plugins/woocommerce-gateway-epay-dk/woocommerce-gateway-epay-dk.php on line 279

**Comment by AllanWLie** [comment]
Hi,

Thank you for reporting this issue. We will look into it and correct the bug(s).
I the meanwhile try to change the "Invoice data" setting in the module configuration and see if this solves your issue.

Thank you for your patience

**Comment by AllanWLie** [comment]
Your issue is solved with the latest release
