### ISSUE TITLE
Ingen callback

### ISSUE THREAD

**Issue by esucces** [ePay/woocommerce#20]
Jeg får ikke en korrekt callback til shoppen, hvad skal jeg kigge efter?

Jeg har opdateret til seneste version 2.6.1.

Transaktionen er godkendt i epay og man ledes fint videre til bekræftelsessiden på shoppen.

**Comment by AllanWLie** [comment]
Hej,
Det er som regel på grund af at det domæne du har registreret hos os ikke matcher den side du sender requests fra.

For at gå dybere ind i sagen, skal du oprette en support sag hos os hvor du skriver dit issue og helst gerne dit merchant nummer og/eller andre relevante informationer, som vi kan bruge til at finde dig i vores system.

Support sagen kan oprettes ved at sende en mail til:  support@bambora.com

Tak
