### ISSUE TITLE
Missing Card Logos

### ISSUE THREAD

**Issue by ttbc** [ePay/woocommerce#23]
Card logos on the checkout page are missing. I've made this custom code to make it work:

       add_filter('woocommerce_gateway_icon', array($this, 'woocommerce_gateway_icon'), 10, 2);

       function woocommerce_gateway_icon($icon, $id) {
            if ( $id === $this->id ) {
                 
                global $woocommerce;
                $cart = $woocommerce->cart;
                $merchantnumber = $this->merchant;
                if(!$cart || !$merchantnumber)
                {
                    return $icon;
                }

                $icon = '<span id="epay_card_logos"></span><script type="text/javascript" src="https://relay.ditonlinebetalingssystem.dk/integration/paymentlogos/PaymentLogos.aspx?merchantnumber='.$merchantnumber.'&direction=2&padding=2&rows=1&logo=0&showdivs=0&cardwidth=45&divid=epay_card_logos"></script>';
            }
            
            return $icon;
      }

**Comment by AllanWLie** [comment]
@ttbc Hi,

Here is a picture of how it looks on our test shop with the newest release of the module:
![image](https://cloud.githubusercontent.com/assets/7969203/21010587/28e7b722-bd4d-11e6-8c32-f552e2958afe.png)


Could you elaborate a bit, perhaps with a picture of the problem you are experiencing?

**Comment by ttbc** [comment]
I'm using WooCommerce 2.6.9 and ePay 2.6.4 (latest versions).
Maybe the icons are somehow stripped out of the description.

![skaermbillede 2016-12-08 kl 14 16 35](https://cloud.githubusercontent.com/assets/3501089/21011354/21732a2c-bd51-11e6-9ab5-5312135efbef.png)

**Comment by AllanWLie** [comment]
@ttbc It seems to something to do with the theme you are using. We are using the standard theme. You can try to change your theme to se if the logo's is still missing.

**Comment by ttbc** [comment]
Ok. So I've successfully testet ePay on another website with another theme and it seems to be working without any problems.

I think the bug could be caused by WPML. I'll look more into this later.
