### ISSUE TITLE
When capture a viabill payment

### ISSUE THREAD

**Issue by Netzie** [ePay/woocommerce#26]
Hi,
I just wanted to capture a ViaBill payment
Error: "Error Fetching http headers"

I use the = 2.6.5 = Version :-) 
(I will upgrade to the 2.6.6. now and hope that helps?)

**Comment by AllanWLie** [comment]
Hi @Netzie

Did the upgrade help ? 

For future issues please try to upgrade before posting an issue.

Have a nice day

-Allan

**Comment by Netzie** [comment]
Hi Allan,

 

I didn’t yet have another viabill to show for.

But I’ll keep my eyes peeled

 

Peter

 

 

Fra: Allan Wamming Lie [mailto:notifications@github.com] 
Sendt: 8. februar 2017 08:42
Til: ePay/woocommerce <woocommerce@noreply.github.com>
Cc: Netzie <peter@bizplanet.dk>; Mention <mention@noreply.github.com>
Emne: Re: [ePay/woocommerce] When capture a viabill payment (#26)

 

Hi @Netzie <https://github.com/Netzie> 

Did the upgrade help ?

For future issues please try to upgrade before posting an issue.

Have a nice day

-Allan

**Comment by AllanWLie** [comment]
@Netzie 
We found an error an it have been fixed in the latest release: https://github.com/ePay/woocommerce/releases/latest
