### ISSUE TITLE
MobilePay vs Dankort

### ISSUE THREAD

**Issue by Netzie** [ePay/woocommerce#27]
Hi
I noticed a little difference...
In my ePay system I saw a payment from MobilePay
But my shop showed a VISA card payment
Everything else is 100% nice and spot on... And I could pull the money - So no complaining 
Would it be possible to detect a MobilePay transaction and show the right logo for it in the shop?
(in time maybe the shop could show how many Mobile payment there was this month as well :) )

Peter

**Comment by AllanWLie** [comment]
Hi @Netzie ,
When a payment is done through Mobile Pay we only registrer the "registered" payment card used in Mobile pay so we are not able to implement your requested feature.

Have a nice day

-Allan
