### ISSUE TITLE
Error after upgrading to the Giraff ...

### ISSUE THREAD

**Issue by Netzie** [ePay/woocommerce#28]
Hi
I just upgraded to the 4.0 Bambora (Giraff) from ePay
Now I get ePay Callback error
1/24 (one pr. hour) When I click the link in the email to check... I get an msg. "Order was already created?

Please advise
I am using iThemes Security . That worked with ePay 3.67

**Comment by Netzie** [comment]
Sorry...It is Bambora 3.0.0 and not 4 :-)

**Comment by AllanWLie** [comment]
Hi,
We need more information that what you are providing. 
Did you remove the old ePay module, and have you checked your settings?
What mail are you talking about ? 

For easier support please contact support@bambora.com

**Comment by Netzie** [comment]
Hi Allan
Yes to both
The mail I am talking about is the Call Back Error email from ePay that comes every hour for 24 hours.

Here is an edited version

Callback could not be made to: 

https://mysite.com/check-exit/ordre-modtaget/8209?key=wc_order_58d40xxxxxxxx&wc-api=Bambora_Online_Classic&wooorderid=8209&txnid=10007xxxxx&orderid=8209&amount=1107200&currency=208&date=20170323&time=1819&txnfee=139&paymenttype=1&cardno=4xxxXXXXXXxxx8&hash=c89e4393130d8a371--------

 Retry count: 7 times. Maximum 24 retries during 24 hours are made.

Error:

The remote server returned an error: (500) Internal Server Error.


I did not change any settings in my iThemes security PRO
Does the new version require any other security stuff than the old ePay version?
Feel free to contact me

https://bizdoktor.dk 

Peter

**Comment by Netzie** [comment]
BTW 
Robin from ePay Support verified for me that the new version would keep my settings when upgrading.
I did also re-check them (password and so).

**Comment by AllanWLie** [comment]
We have found the reason for the error, and we have corrected it. 
You can either update via the WordPress markedplace or use the latest release
https://github.com/ePay/woocommerce/releases/latest

**Comment by Netzie** [comment]
Hi Allan
You are a Ninja - Fast and effective!
Thanks
