### ISSUE TITLE
Possible Error with WooCommerce Subscription

### ISSUE THREAD

**Issue by peterkaer** [ePay/woocommerce#31]
Hi

When deleting an processing order (it went wrong), we get this error that might come from this plugin. Maybe the hook is firing to late, and the subscription is deleted?

Thanks

PHP Fatal error:  Uncaught Exception: Unable to change subscription status to "failed". in /home/forge/*website*/public/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscription.php:312#012Stack trace:#012#0 /home/forge/*website*/public/wp-content/plugins/bambora-online-classic/bambora-online-classic.php(515): WC_Subscription->update_status('failed', 'Bambora abonnem...')#012#1 /home/forge/*website*/public/wp-includes/class-wp-hook.php(298): Bambora_Online_Classic->subscription_cancellation(Object(WC_Subscription))#012#2 /home/forge/*website*/public/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)#012#3 /home/forge/*website*/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array)#012#4 /home/forge/*website*/public/wp-content/plugins/woocommerce-subscriptions/includes/gateways/class-wc-subscriptions-payment-gateways.php(164): do_action('woocommerce_sub...', Object(WC_Subscription))#012#5 /home/forge/*website*/public/wp-includes/class-wp-hook.php(300): WC_Subscriptions_Payment_Gateways::trigger_gat in /home/forge/*website*/public/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscription.php on line 312

**Comment by sorenla** [comment]
Hello peterkaer

Thanks for reporting this. It is indeed an issue with our module. We are working on a fix. Stay tuned.

**Comment by sorenla** [comment]
A new version with a fix for the subscription cancellation bug has been released.
