### ISSUE TITLE
Same error again...

### ISSUE THREAD

**Issue by Netzie** [ePay/woocommerce#32]
Hi
Just opened an order - Click to pull the payment
"Error Fetching http headers"

The money is pulled ... Just don't like red errors :)

Happy Easter

Peter

**Comment by AllanWLie** [comment]
Hi @Netzie 

We can not reproduce your error.

Please send provide a more detailed error description to support@bambora.com

**Comment by Netzie** [comment]
Hi Allan
I think we can delete this one. Maybe a glitch ? I havn't seen the error for a long time now!
Thanks

Peter

**Comment by AllanWLie** [comment]
@Netzie 
Okay I will delete it.

Have a nice day
