### ISSUE TITLE
Visning af transaktionen fejlede - Unable to lookup errorcode

### ISSUE THREAD

**Issue by MPStranger** [ePay/woocommerce#33]
The money is captured, however I see this red error in WooCommerce:
Visning af transaktionen fejlede - Unable to lookup errorcode

**Comment by MPStranger** [comment]
Er der ingen, der læser på disse fejl-beretninger? V. 3.10 har fortsat denne fejl!?

**Comment by sorenla** [comment]
Hej MPStranger

Jeg afviser ikke det kan skyldes en fejl i vores plugin, men umiddelbart tror jeg det skyldes fejl i noget konfiguration. Fejlbeskeden du ser er kommer af fejlhåndteringen i vores plugin ved et fejlet API kald til vores servere - det kan skyldes flere ting, men pluginet gør hvad det kan og melder en fejlbesked.

Til problemer af denne art vil jeg anbefale at skrive til vores support (support@bambora.com). Hvis du skriver "Att: Glenn" i emnefeltet vil Glenn sørge for at din sag bliver sendt videre til mig.
