### ISSUE TITLE
WooCommerce updates (3.0.*-version)

### ISSUE THREAD

**Issue by shvaykovski** [ePay/woocommerce#34]
Please, fix your plug in according to the latest updates from WooCommerce, because currently a lot of errors occur in the system.
E.g.
WC_Order:
id - property is protected and can't be called directly, use get_id() instead.
get_order_currency - deprecated and should be replaced with WC_Order::get_currency
billing_country, shipping_city, shipping_first_name, shipping_last_name, ...  - property should not be accessed directly

**Comment by ViLourenco** [comment]
Hey @shvaykovski, have you fixed by yourself?

**Comment by shvaykovski** [comment]
Yes, but it's better if ePay will fix it. They said that it could take 2-3 weeks (

**Comment by fraefel** [comment]
Hey @shvaykovski, are your patches available somewhere ?

**Comment by shvaykovski** [comment]
@fraefel no, but I just replaces $product->id to $product->get_Id() and other deprecated properties to new methods

**Comment by sorenla** [comment]
The module has just been updated with support for WooCommerce 3.0.
