### ISSUE TITLE
Subscriptions retry system compatibility

### ISSUE THREAD

**Issue by NickGreen** [ePay/woocommerce#36]
When a payment fails, the correct code is not running for Subscriptions failed payment retry system to work correctly.

This line: https://github.com/ePay/woocommerce/blob/master/bambora-online-classic/bambora-online-classic.php#L489

The `process_subscription_payment_failure_on_order()` method is a very old method that was intended to act only on parent orders (it was added before there were renewal orders).

The plugin doesn’t need to call `WC_Subscriptions_Manager::process_subscription_payment_failure_on_order()` anymore.

It should really just call `$renewal_order->update_status( 'failed', $message )` instead of calling `$renewal_order->add_order_note( $message )` and then manually trying to process the failure (mark the order payment as failed and let Subscriptions do the rest automatically).

Stripe provides a good example of doing this: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3.2.3/includes/class-wc-gateway-stripe-addons.php#L280

**Comment by AllanWLie** [comment]
Hi @NickGreen 

Thank you for pointing the error out. We have now corrected it, and a new version is available here https://github.com/ePay/woocommerce/releases/latest and on the WordPress Market

Regards
Allan
