### ISSUE TITLE
adding a parameter

### ISSUE THREAD

**Issue by masterdays** [ePay/woocommerce#37]
according to the instructions here  http://woocommerce.wpguiden.dk/da/opsaetning#66

i must add "description" in the module files...

where is the module file ? and how do i add it ? can u please guide :)

**Comment by AllanWLie** [comment]
Hi @masterdays 

The description is the text that is presented to your customers when they go to the checkout page of your woocommerce. If you want to add or change the default text it is done in the module configuration inside woocommerce.

![image](https://user-images.githubusercontent.com/7969203/34816630-c11c4b5a-f6b5-11e7-8dd8-328bfbb80a08.png)

**Comment by masterdays** [comment]
Hi Allan,

Sorry for not elaborating my question properly.

My question is about sending data to the payment gateway.
It seems possible to add a description to the product which is bought.. do u have any idea of where to insert this description parameter ?

**Comment by AllanWLie** [comment]
Hi again,

Your question is still not clear. Do you want to add a description to the order in the epay administration or du you want to add a description pr. product on the order (Like an invoice) ?

If you want to add it pr. product like an invoice, you can enable this function in the module configuration. (Enable invoice data)

If you want to add a description to the order you will have to add a description element to the payment request array here **https://github.com/ePay/woocommerce/blob/master/bambora-online-classic/bambora-online-classic.php#L602.**

$epay_args = array(
	'encoding' => 'UTF-8',
	'cms' => Bambora_Online_Classic_Helper::get_module_header_info(),
	'windowstate' => $this->windowstate,
	'mobile' => Bambora_Online_Classic_Helper::yes_no_to_int( $this->enablemobilepaymentwindow ),
	'merchantnumber' => $this->merchant,
	'windowid' => $this->windowid,
	'currency' => $order_currency,
	'amount' => Bambora_Online_Classic_Helper::convert_price_to_minorunits( $order_total, $minorunits, $this->roundingmode ),
	'orderid' => str_replace( _x( '#', 'hash before order number', 'woocommerce' ), '', $order->get_order_number() ),
	'accepturl' => Bambora_Online_Classic_Helper::get_accept_url( $order ),
	'cancelurl' => Bambora_Online_Classic_Helper::get_decline_url( $order ),
	'callbackurl' => apply_filters( 'bambora_online_classic_callback_url', Bambora_Online_Classic_Helper::get_bambora_online_classic_callback_url( $order_id ) ),
	'mailreceipt' => $this->authmail,
	'instantcapture' => Bambora_Online_Classic_Helper::yes_no_to_int( $this->instantcapture ),
	'group' => $this->group,
	'language' => Bambora_Online_Classic_Helper::get_language_code( get_locale() ),
	'ownreceipt' => Bambora_Online_Classic_Helper::yes_no_to_int( $this->ownreceipt ),
	'timeout' => '60',
	**'description' => 'YOUR DESCRIPTION'**
);

Regards Allan
