### ISSUE TITLE
PHP 7 - Cant see orders...?

### ISSUE THREAD

**Issue by Netzie** [ePay/woocommerce#38]
Hi 
When I set my site to run PHP7 I enjoy all the benefits on https://herbalcenter.dk - Speed and all :-)
But this plugin is blocking my orders in admin - when I open a order to see it and pull money etc. It only shows the top?? and the rest is blank???
I did some testing and disabled all my plugins... Then it works
So I need to drop back to phop5.6 to see and work with my orders?? :-(
I have another shop with almost the same setup ... and that runs perfectly with bambora
But when I have ALL plugins deactivated (Only WooCommerce and Bambora) it blockes the orders??
If I only have woocommerce active it works

It's a huge job to deactivate all plugins and tests... But after several hours - I can only place the fault on Bambora - So maybe there is something in my codes / database that is messing with something?

I can't really show anything here... (an empty order?) 
But I can provide access and maybe a teamviewer session? 
I am a Bambora Partner (Bizdoktor)
![github-2018-05-01_12-22-17](https://user-images.githubusercontent.com/3857285/39469829-8a04393a-4d3a-11e8-88ac-dcac73c10466.jpg)

Hope someone can help?

Peter

**Comment by AllanWLie** [comment]
Hi @Netzie 

Our plugin for WordPress - WooCommerce is tested with PHP 5.6 and PHP 7.x and we have not seen any errors releated to the PHP version.

Have you tried to uninstall and delete the Bambora module and install the newest version.

**Comment by Netzie** [comment]
Hi Allan,
Wow - You are super fast!!! :-) Thanks mate!
I did a fresh install of the 4.05 version after deactivating and deleting the (4.05) I had ...
Activated php7 - Tested 1-3 orders before activating the plugin... worked!!! .-)
Then activated Bambora 4.05 - all settings was still there !! Super! 
But same error - Still can't see orders? Any chance of a "Hands-On"?

Peter

**Comment by AllanWLie** [comment]
Hi again,

I have tried to replicate your issue on our test shop running PHP 7.0.29 and I can not replicate your issue. Have you checked your WordPress logs ? They can be found either here: "https://yourshop.com/wp-admin/admin.php?page=wc-status&tab=logs"

**Comment by Netzie** [comment]
Hi again,
Thanks
Checked logs .. Nada that is relevant to this (only this:

04-30-2018 @ 23:39:15 - Ingen transaktions id blev fundet for ordre 14850
05-01-2018 @ 13:33:36 - Ingen transaktions id blev fundet for ordre 17064
05-01-2018 @ 13:34:14 - Ingen transaktions id blev fundet for ordre 17064

and those is orders that has no payment with Bambora - That is correct!

Peter

**Comment by AllanWLie** [comment]
Hi again,

On your orders that have not been processed through our module (payment window) do you still, on the order detail page, see the box on the right side with the title "Bambora Online ePay" ?

And what if you make a test order throgh our module (payment window) what do you see then on the order page. 

When you go to the order detail page (that is broken) what does your browser console say (Press F12 and select the console tab)

Have you tried different browsers ?

What version of WordPress are you running?

**Comment by Netzie** [comment]
Hi again,
WP is latest - I keep updating everything 4.9.5-da_DK
I did try 3 diff browsers (FF, Chrome, IE)
Broken order f12 "Console tab" says: JQMIGRATE: Migrate is installed, version 1.4.1 
I can't open any orders -. processed or not - with or without payment - Everything shows up as my picture in 1. post
The "Bambora" box shows up as on the pic in 1. post - No different
Dropping back to PHP5.6 to open orders - Then the Bambora boks don't show up on orders without a transaction (Cancelled orders or pair otherwise)
But Bambora box shows up on orders that have an transaction - Shiny and bright as it looks :-)

**Comment by AllanWLie** [comment]
Hi again,

The Bambora box should only be visible when the order is processed by our module (so your 5.6 is doing it right) 

You can try to install this plugin "PHP Compatibility Checker" I have tested our module with php 7.0, 7.1 and 7.2 all checks out fine. But you should try to run it to see if your PHP 7 installation is correct. 

Another thing when you said that your log was empty, did you try to change the dropdown and see if there were a "Fatal" log ?

**Comment by Netzie** [comment]
Hi again...
I started with the PHP Compa checker !! :-)
To make sure I could - and didn't break anything...
I found the "Fatal log" - **Good thinking...** 
[fatal-error-logfil.txt](https://github.com/ePay/woocommerce/files/1963898/fatal-error-logfil.txt)

That is a game changer.... IT's BIG!!!

So I created a txt file with it - attached
Please delete after review :-) 

Now you might have cracked the nut :)!!!

**Comment by AllanWLie** [comment]
Ahh..... You did not install the php 7 soap client. Example Terminal: "sudo apt-get install php7.0-soap" (please change your php version according to the one you installed)

And also you must enable phpSoap in your php.ini

https://stackoverflow.com/questions/2509143/php-how-do-i-install-soap-extension

**Comment by AllanWLie** [comment]
Also it seems that you have a memory issue. You can also in your php.ini change the amount of allowed memory. 

remember to restart your apache service when done.  (sudo service apache restart)

**Comment by Netzie** [comment]
I will let my HOST know - Powerhosting.dk !! :-(
and get back - hopefully with some good news!!

**Comment by Netzie** [comment]
Hi Allan,
My Sweet Host installed the SOAP and fixed the issues. So now I can first and foremost say:
1: A million thanks for your FAST and effective help - It's SO valuable when trouble arises
2: Thanks for your time and effort 
3: It was NOT Bambora plugin that had the error - but you followed through and helped me anyway and you read the entire message (not just the "first line" ... :-) 👍 

have a fantastic day and thx

Peter

**Comment by AllanWLie** [comment]
Glad to hear that the issue is fixed and thank you for your kind words.

Have a great weekend.

Best regards
Allan - Bambora
