### ISSUE TITLE
Flash of weird string

### ISSUE THREAD

**Issue by EmilEriksen** [ePay/woocommerce#4]
Hi,

If I use the full screen window mode, I'll briefly see a flash of a weird string before I'm redirected to the payment window. It only happens with JS enabled.

![epay-bug](https://cloud.githubusercontent.com/assets/6464323/4130937/a98c169c-333f-11e4-9134-0f888ab8abc1.jpg)

**Comment by sorenla** [comment]
Hello Emil

Thanks for reporting this.

We have note been able to replicate this. Furthermore it seems to be something from another plugin.
