### ISSUE TITLE
Is there any hooks/actions to implement card name  

### ISSUE THREAD

**Issue by martinlyder** [ePay/woocommerce#42]
Hi
I modified the old plugin 2.x to output card name in the order list and on the "New Order email"

In this version I can see that the card name and even logo is shown in the single order view :) But in the code it looks like it's not saved in the order meta data, nut retrieved every-time from ePay serveres.

**Comment by AllanWLie** [comment]
Hi @martinlyder 

We only save the transaction Id in the order meta. Based on that we do a getTransaction to our servers to pull all relevant payment data. 

Have a good day.

-Allan
