### ISSUE TITLE
Dette ville være GREAT

### ISSUE THREAD

**Issue by Netzie** [ePay/woocommerce#44]
Hej
Jeg har mens jeg ventede på papir igennem giraffen benyttet Stripe
På hver ordre ved sammentællingen kan man se gebyret de napper - og hvad man så får i banken!!
Det ville jo være en FED ting også at kunne se i ePay/Bambora modulet?
![stripe-2019-02-21_14-30-16](https://user-images.githubusercontent.com/3857285/53172452-ad224d00-35e5-11e9-924c-52d1b47a3085.jpg)

Do your magic

Peter

**Comment by AllanWLie** [comment]
Hej @Netzie 
Tak for input. Dog er det ikke noget vi kommer til at lave. Vi har ikke noget logik som udstiller de forskellige gebyrer vores merchants får pålagt. 

Men ja ideen er da god. 

Kan du have en god dag.

Med venlig hilsen
Allan
