### ISSUE TITLE
No mention inside the plugin, that "business" plan is required for subscriptions to work

### ISSUE THREAD

**Issue by jespervnielsen** [ePay/woocommerce#46]
It would be nice to see a notice inside the admin area, that if, WooCommerce subscriptions is installed, and this plugin is installed, then output a message stating that it requires the "business plan" to work.
http://www.epay.dk/epay-payment-solutions/priser.asp

We now have a bad experience with a client, because nobody noticed that their current plan wasn't enough.

with subscriptions renewals of 1 year, the renewals started to fail.
After some dialog with Bambora/ePay, it was discovered that they didn't have a high enough plan.
And there was no possible solution to add the current customers on a subscription, without having the users to manually pay (again) and it cost a lot of members to drop out.

**Comment by AllanWLie** [comment]
Hi @jespervnielsen 

We will take this in to consideration. 

Like always please test your integration / solution before going live. Doing so would have caught this long before it would have become an issue for your client. 

Have a good day.

Best regards
Allan - Bambora Online A/S
