### ISSUE TITLE
New capture feature dont do partly...?

### ISSUE THREAD

**Issue by Netzie** [ePay/woocommerce#49]
Hi
I use the new feature when setting orders to "Completed" it automatically pulls out the money.

I edited the amount of an order from 9288,- to 9200,- and and set the order to complete ...
The withdraw was done in Woo but not in ePay manager - So the money is NOT taken/pulled from customer :-(
(Trans-ID: 263157474)

Best regards

Netzie

**Comment by AllanWLie** [comment]
@Netzie 
Please contact support@bambora.com 
The amounts you describe for the transaction id does not match what initial have been authorized. 

Best regards
Allan Lie - Bambora Online A/S

**Comment by Netzie** [comment]
@AllanWLie 
Ehhhh no - That is the part :)
I only wanted to pull out a part of the amount - not the whole amount. 
The last (88,-) was a pickup fee that I didn't want the customer to pay.
