### ISSUE TITLE
The Epay WooCommerce plugin does not work with WooCommerce OnePage-Checkout plugin

### ISSUE THREAD

**Issue by groubee** [ePay/woocommerce#5]
Unfortunately the ePay WooCommerce plugin does not with the WooCommerce Onepage checkout plugin.

**Comment by AllanWLie** [comment]
@groubee  We are not expecting any issues with the WooCommerce Oneapge checkout plugin and our module. 

Could you elaborate on the issues you are having. 

Kind regards
Allan
