### ISSUE TITLE
Delete / Slet / Cancel... No nada?

### ISSUE THREAD

**Issue by Netzie** [ePay/woocommerce#50]
Just installed the latest.. 5.1.3
I did deactivate old... Deleted it and installed the new (activated it)
Did a TEST payment..
My own card... And wanted to clean up

Delete payment dont do nada? - The red button :-(

**Comment by AllanWLie** [comment]
Have you tried to refresh the page after clicking the delete button ? Some times it do not refresh the content of the meta box.

**Comment by Netzie** [comment]
Hi Allan Wamming,

 

Yes – And I did check the payment by logging into epay manager. The payment had to be delete in there.

 

 

Fra: Allan Wamming Lie <notifications@github.com> 
Sendt: 11. august 2020 08:52
Til: ePay/woocommerce <woocommerce@noreply.github.com>
Cc: Netzie <peter@bizplanet.dk>; Author <author@noreply.github.com>
Emne: Re: [ePay/woocommerce] Delete / Slet / Cancel... No nada? (#50)

 

Have you tried to refresh the page after clicking the delete button ? Some times it do not refresh the content of the meta box.

**Comment by AllanWLie** [comment]
Hi again, 
We are unable to replicate the issue you describe. When testing it on our different test shops the transaction is deleted as intended. 
Have you looked in the error / debug log in wordpress. There is a short cut for our module log under the module configuration. 

For further assistance you will need to contact support@bambora.com

Have a good day.

Best regards
Allan Lie - Bambora Online A/S
