### ISSUE TITLE
New update does no longer show payment methods but only Bambora logo

### ISSUE THREAD

**Issue by carcarefreaks** [ePay/woocommerce#51]
Hi,
After upgrading to latest version our shop is only showing the Bambora logo under payment methods and not the possible payment methods as on older version.
![Udklip](https://user-images.githubusercontent.com/33432065/98792723-348da080-2407-11eb-955b-440257abc817.JPG)

**Comment by AllanWLie** [comment]
Hi @carcarefreaks 
This have been fixed in the newest version of the module. (V5.1.5)
