### ISSUE TITLE
Hash validation failed 

### ISSUE THREAD

**Issue by danmag-aps** [ePay/woocommerce#52]
Hash validation failed – Please check your MD5 key Ordrestatus ændret fra Vente for udførelse til Mislykket. 

2020-10-14T17:48:51+00:00 CRITICAL Uncaught Error: Cannot unset string offsets in /var/www/xxxxxx.com/public_html/wp-content/plugins/polylang-pro/vendor/wpsyntex/polylang/include/translated-object.php:167

**Comment by danmag-aps** [comment]
on thank you page: Din ordre kan desværre ikke behandles da banken/indehaveren har afvist din transaktion. Forsøg venligst at bestille igen. 

in woocomerce administration: Hash validation failed – Please check your MD5 key Ordrestatus ændret fra Vente for udførelse til Mislykket. 

-
we using a woo subscription plugin too...

**Comment by AllanWLie** [comment]
Hi @danmag-aps 

Please contact support@bambora.com

Best regards
Allan - Bambora Online A/S
