### ISSUE TITLE
Fatal error after 5.1.5 update

### ISSUE THREAD

**Issue by zzbeck** [ePay/woocommerce#54]
Hi,
After the recent update, we get a fatal error. It seems like some kind of conflict with our payment plugin Scanpay.
I have also notified Scanpay.

I have downgraded to the previous version.

`Fatal Error: Uncaught ArgumentCountError: Too Few Arguments To Function WC_Scanpay::Add_card_icons(), 1 Passed In /Public/Wp-Includes/Class-Wp-Hook.php On Line 287 And Exactly 2 Expected In /Wp-Content/Plugins/Scanpay-For-Woocommerce/Includes/Gateway.php:101 Stack Trace: #0 /Wp-Includes/Class-Wp-Hook.php(287): WC_Scanpay->Add_card_icons('<Img Src="Https...') #1 /Public/Wp-Includes/Plugin.php(206): WP_Hook->Apply_filters('<Img Src="Https...', Array) #2 /Wp-Content/Plugins/Bambora-Online-Classic/Bambora-Online-Classic.php(1298): Apply_filters('Woocommerce_gat...', '<Img Src="Https...') #3 /Public/Wp-Content/Plugins/Woocommerce/Templates/Checkout/Payment-Method.php(26): Bambora_Online_Classic->Get_icon() #4 /Wp-Content/Plugins/Woocommerce/Includes/Wc-Core-Functions.php(345): Include('/Srv/Users/Evi In Wp-Content/Plugins/Scanpay-For-Woocommerce/Includes/Gateway.php On Line 101`

**Comment by sessan** [comment]
@zzbeck Hi! 
This compatibility issue is now fixed in the v5.2.0 of our plugin.
Best Regards
Jessica Björkäng - Bambora Online
