### ISSUE TITLE
Does not work with newer versions of Woocommerce and Wordpress

### ISSUE THREAD

**Issue by Teslafied** [ePay/woocommerce#8]
I'm running Woocommerne 2.4.12 and Wordpress 4.4.
When trying to make a payment it just showes the frosted overlay and then goes back to checkout page.
Quite critical.

Website is teslafied.eu if you wanna see it.

**Comment by Saphant** [comment]
Hi, could you provide me an example of this?
Would be happy to try help out!

**Comment by Teslafied** [comment]
Hi,
I have already been solved by Epay.
Where are problem with WPML.
