### ISSUE TITLE
Incompatible with WooCommerce Subscriptions

### ISSUE THREAD

**Issue by stefanmf** [ePay/woocommerce#9]
The module does not work properly with WooCommerce Subscriptions 2.x, resulting in a flood of payment requests on subscription renewal.

**Comment by jonasskafte** [comment]
+1

In my case, after a while trying, the pop-up fails to load completely. The 'pay with ePay' button on the fall-back page doesn't work either :-(

Hope there will be a fix soon (I'd provide it myself if only I knew how to) as otherwise we'll have to use a different gateway.

Have a nice Easter!

**Comment by jonasskafte** [comment]
For the record, I've diagnosed our issue to having to do with CloudFlare's Wordpress plug-in and not WooCommerce Subscriptions. I've reported this here:

#13

**Comment by sorenla** [comment]
Hello Stefan

This should be fixed in the [latest release](https://github.com/ePay/woocommerce/releases/latest).
